stages:
  - build
  - deploy

variables:
  IMAGE: "$REGISTRY_URL/dragospaul/bun-nestjs"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-image:
  stage: build
  tags:
    - docker
  image: docker:28.4-cli        # job container with docker client
  services:
    - docker:28.4-dind          # DinD sidecar for builds
  script:
    - echo "$REGISTRY_PASS" | docker login $REGISTRY_URL -u "$REGISTRY_USER" --password-stdin
    - docker build -t $IMAGE:$CI_COMMIT_SHA -t $IMAGE:latest .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
  only:
    - master

deploy:
  stage: deploy
  tags:
    - docker
  image: curlimages/curl:latest
  script:
    - 'curl -X POST "$DOKPLOY_WEBHOOK_URL"'
  only:
    - master