stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""   # disable TLS dir inside DinD
  DOCKER_DRIVER: overlay2
  IMAGE: "$REGISTRY_URL/dragospaul/bun-nestjs"

services:
  - docker:dind

build-image:
  stage: build
  tags:
    - docker   # must match your runner tag
  image: alpine:latest
  script:
    - echo "$REGISTRY_PASS" | docker login $REGISTRY_URL -u "$REGISTRY_USER" --password-stdin
    - docker build -t $IMAGE:$CI_COMMIT_SHA -t $IMAGE:latest .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
  only:
    - master

deploy:
  stage: deploy
  tags:
    - docker
  image: curlimages/curl:latest
  script:
    - 'curl -X POST "$DOKPLOY_WEBHOOK_URL"'
  only:
    - master