stages:
  - build
  - deploy

variables:
  IMAGE: "$CI_REGISTRY_IMAGE"   # built-in: registry.gitlab.verdedata.ro/dragospaul/bun-nestjs
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-image:
  stage: build
  tags:
    - docker
  image: docker:28.4-cli
  services:
    - docker:28.4-dind
  script:
    # Log in with built-in CI job token
    - echo "$CI_JOB_TOKEN" | docker login "$CI_REGISTRY" -u gitlab-ci-token --password-stdin
    # Build + tag images
    - docker build -t $IMAGE:$CI_COMMIT_SHA -t $IMAGE:latest .
    # Push both commit SHA tag and latest
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
  only:
    - master

deploy:
  stage: deploy
  tags:
    - docker
  image: curlimages/curl:latest
  script:
    - 'curl -X POST "$DOKPLOY_WEBHOOK_URL"'
  only:
    - master